version: '4'

services:
  mysql: #Salt
    container_name: MySQL
    image: mysql:8.0
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'volkansezer'
      MYSQL_USER: 'volkan'
      MYSQL_PASSWORD: 'sezer'
      MYSQL_ROOT_PASSWORD: 'sezer'
      MYSQL_ALLOW_EMPTY_PASSWORD: true

  phpmyadmin: #Salt
    container_name: PHPMyAdmin
    image: phpmyadmin/phpmyadmin
    links:
        - mysql
    environment:
      PMA_HOST: mysql     #PMA nerede çalışacak, oluşturduğumuz @4 "mysql" de çalışacak, onun adını veriyoruz 
      PMA_USER: root
      PMA_PASSWORD: sezer
    depends_on:
      - mysql
    ports:
      - "8081:80"

  php:
    container_name: PHP
    image: volkansezer/phpmysqli
    # kurulumdan sonra Terminalde aç docker-php-ext-install mysqli komutunu çalıştır
    volumes:
      - "./volumes/php/www:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 8080:80 